---
# file: .travis.yml

language: python

python:
  - "2.7"
  - "3.6"

services: docker

env:
  matrix:
    - MOLECULE_DIST: 'jam82/arch-molecule:latest'
    - MOLECULE_DIST: 'jam82/ubuntu-molecule:16.04'
    - MOLECULE_DIST: 'jam82/ubuntu-molecule:18.04'

install:
  - pip install testinfra molecule docker

script:
  - molecule --version
  - ansible --version
  - molecule test
