---
# role: ansible-role-vscode
# file: .travis.yml

os: linux
dist: focal

language: python

branches:
  only:
    - main

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install ansible yamllint ansible-lint

script:
  - ansible-lint
